IO use cases added to icb_bitstream
os-fpga/Jira_Testcase pull request #103
Opened 2024-04-02 07:41 UTC by valence-e

2024-04-02 16:22 UTC, alaindargelas approved these changes

2024-04-02 16:22 UTC, alaindargelas commented on icb_bitstream/o_ddr_o_buf/o_ddr_o_buf.v
> +
Missing I_BUF before the CLK_BUF

2024-04-02 16:22 UTC, alaindargelas commented on icb_bitstream/o_ddr_o_buf/o_ddr_o_buf.v
> +
Missing I_BUF for all inputs

2024-04-02 17:08 UTC, alaindargelas commented
@ashrafnisar , please review

2024-04-03 05:51 UTC, ashrafnisar requested changes
Add I_BUF and O_BUF primitives for all the primary inputs and outputs.

2024-04-03 06:52 UTC, closed without merging